services:
  nginx:
    image: nginx:latest
    ports:
      - 9001:80
    volumes:
      - ./html:/usr/share/nginx/html
      - nginx_data:/var/lib/nginx
    networks:
      - nginx-network
volumes:
  nginx_data:
  
networks:
  nginx-network:
    driver: bridge
